### ISSUE TITLE
auto resume

### ISSUE THREAD

**Issue by zajaklis** [karawin/Ka-Radio#1]
At fist i wanted to thank you for you hard work and time spent on this project.

This not an issue, but more like feature request.
It would be nice that device on startup starts automatically playing radio station which was running before shutdown.
At fist i thought that its configurable on webui with "AutoPlay" checkbox, but it did not do anything.
What AutoPlay checkbox does?

**Comment by karawin** [comment]
Hello,

Thanks,

Yes, the autoPlay is only after the first play button pressed. After 
that, any other selection is launched automatically.
I forgot to launch the current station. I will work on it soon.


Regards

JP

**Comment by zajaklis** [comment]
hi again, did you implemented auto resume feature?
i have not notice that in changelog.

**Comment by karawin** [comment]
Partially.
The problem is that the knowing is not in the esp but in the browser.
I have to add it on the esp eprom.... Soon.

**Comment by karawin** [comment]
autostart: test these bin....
I think it will works now.
thanks

**Comment by zajaklis** [comment]
which bins include autostart feature?

**Comment by karawin** [comment]
Both.

Two bin, one for each bank.

Try just the 1.

**Comment by zajaklis** [comment]
took from http://karadio.karawin.fr/ and autoplay still not working after applying power.
Idea was to interact  with ka-radio without webui. At the moment after applying power im counting till 10 and pressing play button.

**Comment by karawin** [comment]
Normal, it is not delivered, the bin was a preview .

**Comment by karawin** [comment]
The 1.0.9 is released and working ;-)

**Comment by zajaklis** [comment]
Great, just tested, all works!
Thank you
