### ISSUE TITLE
Suggestion: Enable signal for amplifier

### ISSUE THREAD

**Issue by HcDevel** [karawin/Ka-Radio#10]
Hello,

I succesfully flashed Ka-Radio and attached it to a Class-D amplifier module to replace my current amplifier. Now I would like to turn off the amplifier when playback stopped to save energy. Using a relais or transistor shouldn't be a problem, but I need a signal which I can use to switch the transistor. The signal needs to be high while playing and low while not playing.
Is there already a pin configured I could use for this?

**Comment by karawin** [comment]
No problem, it is easy to add it but in the pro mini arduino lcd software only because of the lack of gpio on the esp8266.
Even if you don't have a lcd connected, it is easy to add an output on the pro mini for that purpose.
I will add it in the karadioU8Glib software v1.3 soon.
