### ISSUE TITLE
Play password protected streams and support for https urls

### ISSUE THREAD

**Issue by totalizator** [karawin/Ka-Radio#11]
I'm trying to play password protected streams. Such url looks like: **user:password@www.radio.org**. It looks like it's not supported right now.

Other thing is - what would be needed to play streams via https?

**Comment by karawin** [comment]
No, it is not and will not be, sorry.
This feature need a |WWW-Authenticate: field and base64 cryptage.

Feasable but....
Same for https. Never seen a webradio with https.


|

**Comment by totalizator** [comment]
That's OK. 

The question was about my private streams that are intentionally exposed to the internet and using https is the simplest method for securing the url. No worries though. There are plenty of other methods.

Thank you for the clarification.
