### ISSUE TITLE
cannot change IP

### ISSUE THREAD

**Issue by yo2ldk** [karawin/Ka-Radio#2]
Hi,

  this is a very nice and well made it project, Thank you!
I do something wrong maybe, because when I try to put AP name, pswd , a new IP and gateway, this is not happening , it comes back on 192.168.4.1 and I have no connection to internet for ESP module.
on router I have ...1.1, try it also with original class ...8.1 and with ...0.1 , all the same.
I not have memory IC (until I get it),  but it work also without it, no? and when ESP have no power, I need to rewrite all settings in this case?
 sorry for all questions, but I am more on hardware and a beginner in codding .

**Comment by karawin** [comment]
Hi

Firstly check if you have a 4Mb esp8266 (ie 32mbits)

Le 16/07/2016 à 06:55, alexander - yo2ldk a écrit :
>
> Hi,
>
> this is a very nice and well made it project, Thank you!
> I do something wrong maybe, because when I try to put AP name, pswd , 
> a new IP and gateway, this is not happening , it comes back on 
> 192.168.4.1 and I have no connection to internet for ESP module.
>
May be a wrong AP or password?
Before all, make a "Clear stations" and after change the wifi setting: 
No dhcp, an ip address in 192.168.1.x a mask of 255.255.255.0 and the ip 
of your router.


> on router I have ...1.1, try it also with original class ...8.1 and 
> with ...0.1 , all the same.
> I not have memory IC (until I get it), but it work also without it, 
> no? and when ESP have no power, I need to rewrite all settings in this 
> case?
> sorry for all questions, but I am more on hardware and a beginner in 
> codding .
>

Yes it works without the external ram.
Check for a 4MB esp8266 if the stations are not maintened, it may be the 
problem.
If it is the wifi setting not maintened, it is because the internet AP 
access is wrong.

**Comment by yo2ldk** [comment]
Thank you for fast reply
 I try for 3 days already and no conclusion..
yes my esp board have 4Mb is wemos esp d1 mini, but I try also with NodeMcu v.3 the same thing
 firmware is well flashed ,router is ok, password all good but not connect
web interface it is and work ok, full level of wifi, connections is made it conf. pdf. file; i'm stuck...  :)

**Comment by karawin** [comment]
Try the uart interface (documented in 
\a-Radio\ESP8266-Firmware\documents\uartinterface.txt):

sys.erase
wifi.list
wifi.con("ssid","password")
wifi.status

Bye

JP

**Comment by yo2ldk** [comment]
Merci beaucoup !

**Comment by karawin** [comment]
Check also your power. It is very sensitive. A good external power 
supply is needed.

**Comment by yo2ldk** [comment]
I use power bank Xiaomi 16000 mA

**Comment by karawin** [comment]
115200b/s ?
try http://www.compuphase.com/software_termite.htm
Press enter key, you must see
#INFO:""#

If not, the flash is not good.

**Comment by yo2ldk** [comment]
sorry to bother you with my problem;
I use tera term, also realterm, now on termite when push enter nothing appear. all on 9600
testing also with 115200
web page look ok, I reflashing, last solutions here.

**Comment by yo2ldk** [comment]
for sure i wrong somthing..
after reflashing two modules, with serial connection I have no response from any.  at all !
 I flash as follow:

boot_v1.5 at 0x00000
user1.4096.new.4.bin at 0x1000 ,
user2.4096.new.4.bin at 0X81000
blank.bin at 0x7e000 
blank.bin at 0x3fe000

it is ok that?  because I don't know what to do more..

**Comment by karawin** [comment]
The complete flash is
![flash](https://cloud.githubusercontent.com/assets/7613191/16895956/79cf8b72-4b85-11e6-83ad-60516dea0df1.png)

With what tool do you flash it?
Under windows or linux? 
Do you have checked all wires? Try without the vs1053 in case of doubt.

**Comment by karawin** [comment]
no news?

**Comment by yo2ldk** [comment]
Jean-Pierre, 
Thank you for all your help, especially latest, with photo !
 in the first time, I write firmware exactly like you except latest two file .  
 Now i write all files, on four (4) different modules. 
 on all when I try to access with terminal (5 different software) I get nothing or strange char.
not what should be. 
I'm not so stupid, i load firmware in many and different equipment's but with that this is like I fell.. 
 so , I take a break, maybe in this weekend I made latest try, even if I need this Radio.
 my best regards,

                 alex.

**Comment by karawin** [comment]
![termite1](https://cloud.githubusercontent.com/assets/7613191/17258734/979dec64-55c8-11e6-81c3-bc16afe16c88.png)
