### ISSUE TITLE
Nextion hmi

### ISSUE THREAD

**Issue by AST-esp-rasp** [karawin/Ka-Radio#20]
Hello,
You have done a great job!!!
Controlling Kia radio with nextion hmi seems to work (waiting for my display used simulation softwre from nextion). Now I'm wondering if some additional printf commands in webserver and client would allowing to get correct feedback for the display. Actually i could see there ##CLI.xxx# strings printed.
Would it harm the code when im adding an additional printf with my nextion instruction string?
And of course it only works when i figure out how to compile it?

**Comment by karawin** [comment]
see http://karadio.karawin.fr/Interface.txt for the complete list of commands and prints

**Comment by karawin** [comment]
Just add a 3$ µc with 2 serial interfaces and write your own software. It is very easy and much more easy to debug and update.

**Comment by AST-esp-rasp** [comment]
That's true! It will save a lot of effort! 
But it won't be the most sophisticated solution.
