### ISSUE TITLE
Purging the entire station list causes strange lockups on boot

### ISSUE THREAD

**Issue by NonaSuomy** [karawin/Ka-Radio#23]
Had to keep resetting the unit until I was able to get back in for a second to upload the sample station list, then it stabilized again.

Also after you delete the entire list there doesn't seem to be a way to add one station back without importing a list. The station screen was empty no edit buttons until the import.

**Comment by karawin** [comment]
I can't see the same problem.

**Comment by NonaSuomy** [comment]
OTA updated to 1.1.8 and it seems fine now :+1:
