### ISSUE TITLE
Playing resumes after pressing stop while power is on

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#30]
Steps to reproduce:
- start playing 
- stop by hardware button or  via webui 
- playing resumes after some time (from few seconds to several minutes) 
I expected no playing after pressing stop button. 
The issue is reproducible on v1.2.1

**Comment by karawin** [comment]
Please Check adc to gnd connection.

**Comment by karawin** [comment]
Sorry, not seen the hardware button...
Are your wires longs? May be an interference...

**Comment by romankot** [comment]
Hardware button board connected with devkit with wires no more than 10cm long. Moreover volume buttons don't work every time correctly, next/previous works fine as well as stop/start

**Comment by karawin** [comment]
This panel is very sensitive to the 3.3v accuracy and stability (and 
resistors precisions).
Check  to see if it is really 3.3 volts. The adc must be at 1.0 volt 
when no button in action

**Comment by karawin** [comment]
No news?
