### ISSUE TITLE
Update via webinterface fails

### ISSUE THREAD

**Issue by hcremer** [karawin/Ka-Radio#33]
Hi,
when trying to update from version 1.3 (flashed via USB) to version 1.3.1 via Webinterface, it leaves the version number in the upper right corner on V1.3 (also after cache erase in the webbrowser)

The serial terminal says:

"update  firmware
current id 0
flash size  4
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
flash erase over
userbin sumlength:410164  flash:1
Connect ok!
Request send success
userbin sumlength:410164 
server response with something else,check it!
upgrade data error!
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
flash erase over
userbin sumlength:410164  flash:1
Connect ok!
Request send success
userbin sumlength:410164 
server response with something else,check it!
upgrade data error!
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
flash erase over
userbin sumlength:410164  flash:1
Connect ok!
Request send success
userbin sumlength:410164 
server response with something else,check it!
upgrade data error!
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
flash erase over
userbin sumlength:410164  flash:1
Connect ok!
Request send success
userbin sumlength:410164 
server response with something else,check it!
upgrade data error!
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
flash erase over
userbin sumlength:410164  flash:1
Connect ok!
Request send success
userbin sumlength:410164 
server response with something else,check it!
upgrade data error!
spi_flash_read error 1
 Exit upgrade task.
 +OK: FW upgrade success.
reboot to use2
state: 5 -> 0 (0)
rm 0
pm close 7 0 0/341787327
del if0
usl
##CLI.STOPPED# from try restart
 ets Jan  8 2013,rst cause:2, boot mode:(3,0)
load 0x40100000, len 2408, room 16 
tail 8
chksum 0xe5
load 0x3ffe8000, len 776, room 0 
tail 8
chksum 0x84
load 0x3ffe8310, len 632, room 0 
tail 8
chksum 0xd8
csum 0xd8
2nd boot version : 1.6
  SPI Speed      : 40MHz
  SPI Mode       : DIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user2 @ 81000
error magic!
first boot failed, reboot to try backup bin
 ets Jan  8 2013,rst cause:4, boot mode:(3,0)
wdt reset
load 0x40100000, len 2408, room 16 
tail 8
chksum 0xe5
load 0x3ffe8000, len 776, room 0 
tail 8
chksum 0x84
load 0x3ffe8310, len 632, room 0 
tail 8
chksum 0xd8
csum 0xd8
2nd boot version : 1.6
  SPI Speed      : 40MHz
  SPI Mode       : DIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user1 @ 1000
~r⸮⸮b
=> extraram state: 0 0xff ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
SDK 1.4.2(f57d61a)
data  : 0x3ffe8000 ~ 0x3ffe899a, len: 2458
rodata: 0x3ffe89a0 ~ 0x3ffeb1ec, len: 10316
bss   : 0x3ffeb1f0 ~ 0x3fff2150, len: 28512
heap  : 0x3fff2150 ~ 0x40000000, len: 57008
Heap size: 29224
size_map: 4
t0 task: 3fff8f88
t1 task: 3fff9198
t4 task: 3fff96a0
t3 task: 3fff9cc0
t2 task: 3fffa8d0
Heap size: 21312
mode : sta(XX:XX:XX:XX:XX:XX)
add if0
watermark:336  heap:19928
SCI_Mode (0x4800) = 0x4802
SCI_Status (0x48) = 0x4C
VS Version (VS1053 is 4) = 4
p: XXX.XXX.X.XXX
scandone
Trying XXX,  I: 0 status: 1
scandone
state: 0 -> 2 (b0)
Trying XXX,  I: 1 status: 1
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
pm open phy_2,type:2 0 0
cnt 
connected with XXX, channel 10
dhcp client start...
ip:XXX.XXX.X.XXX,mask:255.255.255.0,gw:XXX.XXX.X.X
autostart: playing:1, currentstation:3
I2S Speed: 0
##CLI.STOPPED# from playStationInt
##CLI.NAMESET#: 3 WDR5
##CLI.URLSET#: wdr-wdr5-live.icecast.wdr.de
##CLI.PATHSET#: /wdr/wdr5/live/mp3/128/stream.mp3
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 90
##CLI.ICY0#:  WDR 5, Westdeutscher Rundfunk Koeln
##CLI.ICY3#:  http://www.wdr5.de
##CLI.ICY4#:  wdr
##CLI.ICY6#:  Westdeutscher Rundfunk Koeln
##CLI.PLAYING#
##CLI.META#: WDR 5 Hotline: 0221-56789 555
##CLI.META#: WDR 5 - Ich will es wissen
##CLI.META#: Westblick - Das Landesmagazin mit Edda Dammmüller"

I assume the flashing did not work because of several "upgrade data error!".
I don't understand the:
"spi_flash_read error 1
 Exit upgrade task.
 +OK: FW upgrade success."

What can I do to get the update via webinterface working?

Best regards,
H. Cremer

**Comment by karawin** [comment]
I see
server response with something else,check it!

Don't know why. 

Try again please.

The "spi_flash_read error 1
Exit upgrade task.
+OK: FW upgrade success."

means a problem in the update but a normal exit of the upgrade task.

I hope that it is not due to the DIO mode.

**Comment by hcremer** [comment]
Thank you for replying so soon!
Tried it before with previous versions. No result. Flashed manually to 1.3 via USB (1 DIO chip 1 QIO chip).
Tried the same webupdate with the QIO chip. Same result.
How do I check the server response? Would Wireshark be a possibility? Unfortunately, I only have nearly no experience with this tool.
Could it be possible because of my IPFire-Firewall? Do you use other ports than 80 for the update?

**Comment by karawin** [comment]
So, i think that 
"server response with something else,check it!"
 is an error message from the firewall.

**Comment by karawin** [comment]
void update_firmware(void)
{
    printf("update  firmware\r\n");
    uint8 current_id = system_upgrade_userbin_check();
    os_printf("current id %d\n", current_id);

	char* client_url = "karadio.karawin.fr";
//	char* client_url = "192.168.1.2";
#define bin_url  "user%d.4096.new.4.bin"
    struct upgrade_server_info *server = NULL;
    server = (struct upgrade_server_info *)malloc(sizeof(struct upgrade_server_info));
    memset(server, 0, sizeof(struct upgrade_server_info));
    server->check_cb = user_esp_upgrade_rsp;   //set upgrade check call back function
    server->check_times = 360000;
	server->upgrade_flag = true;
	
    if (server->url == NULL) {
        server->url = (uint8 *)malloc(512);
    }

    flash_size_map f_size = system_get_flash_size_map();
    os_printf("flash size  %d\n",f_size);
    if (current_id == 0) {
		 current_id = 2;
	} else current_id = 1;
    sprintf(server->url, "GET /"bin_url" HTTP/1.0\r\nHost: %s:80\r\n"pheadbuffer"",current_id, client_url);
//   os_printf("http_req : %s\n", server->url);
	
	struct hostent *serv ;
	serv =(struct hostent*)gethostbyname(client_url);
    server->sockaddrin.sin_family = AF_INET;
    server->sockaddrin.sin_port   = htons(80);
    server->sockaddrin.sin_addr.s_addr = inet_addr(inet_ntoa(*(struct in_addr*)(serv-> h_addr_list[0]))); // remote server ip
//	os_printf("distant ip: %x   ADDR:%s\n",server->sockaddrin.sin_addr.s_addr,inet_ntoa(*(struct in_addr*)(serv-> h_addr_list[0])));
    if (system_upgrade_start(server) == false) {
        os_printf("upgrade error\n");
    }

**Comment by hcremer** [comment]
Tried it with no firewall (directly connected to the fritzbox wlan)
Result: No more reaction from the chip after web-upgrade. Needed to be re-flashed by USB to get it working again.

Serial terminal output:

update  firmware
current id 1
flash size  4
Connect ok!
Request send success
pre erase flash!
userbin sumlength:410164 
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)
wdt reset
load 0x40100000, len 2408, room 16 
tail 8
chksum 0xe5
load 0x3ffe8000, len 776, room 0 
tail 8
chksum 0x84
load 0x3ffe8310, len 632, room 0 
tail 8
chksum 0xd8
csum 0xd8
2nd boot version : 1.6
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
enhance boot mode, jump to run bin @ 1000
 @ 1000
error magic!
first boot failed, reboot to try backup bin
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)
wdt reset
load 0x40100000, len 2408, room 16 
tail 8
chksum 0xe5
load 0x3ffe8000, len 776, room 0 
tail 8
chksum 0x84
load 0x3ffe8310, len 632, room 0 
tail 8
chksum 0xd8
csum 0xd8
2nd boot version : 1.6
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
enhance boot mode, jump to run bin @ 1000
 @ 1000
error magic!
backup boot failed.
user code done

**Comment by hcremer** [comment]
When I try http://karadio.karawin.fr/ in a webbrowser, I get:
Forbidden

You don't have permission to access / on this server.
Apache/2.4.10 (Ubuntu) Server at karadio.karawin.fr Port 80

**Comment by karawin** [comment]
In your log, the flash is erased then a watchdog reset occured. So It fails and cannot restart because the flash is erased.
Try again by reflashing manually. I don't know why the watchdog has been reached.

 http://karadio.karawin.fr is a file repository. I deny all other access. (no index.html)

**Comment by hcremer** [comment]
I have no idea why, but the both chips (DIO and QIO) chip had the same problem:
Both had the watchdog problem at first attempt to upgrade via webinterface.
Both reflashed to 1.3 via USB.
Then upgraded via webinterface, cleared the browser cache and its on 1.3.1 :-)
To add to the log on hackaday anothe DIO chip is the "ESP-12F" labelled chip from https://www.banggood.com/Geekcreit-ESP-F-ESP8266-Remote-Serial-Port-WiFi-IoT-Module-Nodemcu-LUA-RC-Authenticity-p-1127307.html?rmmds=search

I would like to do a donation but paypal wants my address and phonenumber but I'm not willing to give it to them. Could you please give me an IBAN and BIC to send the money directly to you?

**Comment by karawin** [comment]
Thanks.
To answer you, Send me an email directly. 
jp@karawin.fr
paypal is safe (but who can be sure?)  no problem.

I have to analyse the update more deeply to found the cause. 
I want a perfect software (if possible ;-)
