### ISSUE TITLE
No sound after 1.3.1 update

### ISSUE THREAD

**Issue by nlovrens** [karawin/Ka-Radio#34]
Hi, I had my karadio working perfectly on v1.1.7. All i did was click on upgrade from web interface (didn't change or touch any other settings). Now I am running version 1.3.1 and everything looks like working but no sound is coming from VS1053 module.
Did something changed regarding hardware from v1.7.1 to v.1.3.1? I also have optional external RAM (23LCV1024) if that is relevant.
P.S. Thank you for all your great work regarding this project

**Comment by karawin** [comment]
Try to disable the patch loading with uart command
sys.patch("0")

Some non vs1053b doesn't support the patch for aac even if it is detected as vs1053.

**Comment by nlovrens** [comment]
Hi,
It works after disabling patch.
Thank you

**Comment by karawin** [comment]
You are welcome
