### ISSUE TITLE
Telnet command "help" doesn't work

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#38]
reproducible on 1.4.2

**Comment by karawin** [comment]
On putty: connection telnet negotiation mode: passive

**Comment by romankot** [comment]
Thanks. it worked. Is it possible to avoid making this special config ? The rest commands are working somehow

**Comment by romankot** [comment]
having complete webinterface would be much nicer comparing to oldschhol telnet

**Comment by karawin** [comment]
http://yourEspIp
