### ISSUE TITLE
No AP point after flash, 

### ISSUE THREAD

**Issue by Edragon** [karawin/Ka-Radio#41]
after flashed the frimware, I get this from serial:

rl\0l湠|\0宭鄚?l?b|巶?抮抌?b岒nn瀕nn溾?bp鞄$rlrlp餹??lbn鈢??b岒nn頫0l寧l`?nnl`nr帓抧拻l`p騨?r寽溾?bn鈢鞄帋b岒nn頫0l`?nnl`nr帓抧?lp騨?r寽溾囔lbn鈢寧?b岒nn頫0l`?nnl`nr帓抧?l`r拻n?l`rl寣n湆騨n瀸炩宺nnn?l宐?l\0?抣?拻??巐ll~rl\0?抣lln溾\0?悓~抈\0?抣寪n鄮n鞉n~寣ll鄝b鞂llpb?br倢靗`nl巔岇l`bl`l拻n瀗寬鈔l瀨bll`rl~r?恇\0尀鈱bl宐r|lb溾?bp鈘鞄l\0祢n顎nn?ll噔l鞄?l鞄l宭鞂岇l`€n黒0尀鈱bll巖?b尀鈱bl宐?lrl屸?俷鞉r傭n|?llll`恟n?炧?
=> extraram state: 0 0xff 
Release 1.5, Revision 0
SDK 1.5.0-dev(1aafc07)
data  : 0x3ffe8000 ~ 0x3ffe8928, len: 2344
rodata: 0x3ffe8930 ~ 0x3ffe8b2c, len: 508
bss   : 0x3ffe8b30 ~ 0x3fff00c0, len: 30096
heap  : 0x3fff00c0 ~ 0x40000000, len: 65344
Heap size: 37048
size_map: 4
t0 task: 3fff70f0
t1 task: 3fff7350
t4 task: 3fff7a60
t3 task: 3fff7e50
t2 task: 3fff83f8
t5 task: 3fff87e8
t6 task: 3fff8e30
Heap size: 27520
mode : sta(60:01:94:3b:57:21)
add if0

but there is no AP point called, ssid "WifiWebRadio". Did I flash the firmware probably? Thank you very much!

**Comment by karawin** [comment]
The vs1053 acces is blocking. 
Check the DREQ line or disconnect it to be sure it is the problem.

**Comment by Edragon** [comment]
Yes, indeed, all good, serial output correctly. probably some soldering problem, when I have vs1053 all work. 

Thank you very much.

**Comment by Edragon** [comment]
Hi Karawin,

Yes one more question, there is a wiring instruction in the readme.md:
From ESP8266_ESP12( 3.3 v) to VS1053 (5 v)
REST
ADC if control panel is not used, this input must be grounded.
CH_PD to 3.3v
GPIO16 (a 1Hz output)
GPIO14 to VS1053 SCK
GPIO12 to VS1053 MISO
GPIO13 to VS1053 MOSI

TXD to CH340G UART rx
RXD from CH340G UART tx
GPIO05 to VS1053 XDCS
GPIO04 to VS1053 DREQ
GPIO00 to VS1053 XRST
GPIO02
GPIO15 to VS1053 XCS

But there is also a schematic called webradio in hardware folder, should I use the readme.md wiring?  Thanks!

**Comment by Edragon** [comment]
in the schematic pdf, io5 is connected to DREG, I am not sure if it is the wiring problem.

**Comment by karawin** [comment]
This schematic is the old one from piotr. Don't use it.
DREQ is on GPIO04 (d2)

**Comment by Edragon** [comment]
good to know, thanks!
