### ISSUE TITLE
Support Cyrillic characters required for channel/song name

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#42]

**Comment by karawin** [comment]
Only by the browser. not by serial or telnet.

**Comment by romankot** [comment]
Terminal doesn't show Cyrillic fonts. Should I change remote character set on putty to see Cyrillic ?

**Comment by karawin** [comment]
I don't know. Only the basic char stream is sent.
See it on a browser.
![russe](https://user-images.githubusercontent.com/7613191/28752210-483578a0-751a-11e7-9d06-8783aa4addb2.jpg)

**Comment by romankot** [comment]
you see 

![cyrilliccharsissue](https://user-images.githubusercontent.com/1821783/28862487-e88b7cc8-776d-11e7-9980-0aefcece675e.png)

**Comment by karawin** [comment]
This station http://uk5.internet-radio.com:8112/live.m3u is not in cyrillic and it seems that the browser don't know the translation if possible.

**Comment by karawin** [comment]
Cannot do something for that.

**Comment by arlaor** [comment]
Hi @karawin 

Until version 1.4.2 I was able to update the project, but with versions 1.5 and 1.5.1 does not take the changes and is maintained in version 1.4.2.
Can you add a warning next to the upgrade button, which lets you know if the project is being updated or not?
I have done the same steps for the previous updates but in version 1.5 has not taken the changes.
Thanks

**Comment by karawin** [comment]
On the serial interface or telnet do a sys.update
if unsuccesfull, it is clearly written.
In this case do a sys.prerelease
Things must be right now.

**Comment by arlaor** [comment]
The system Prerelease Should I do it for some special program?

**Comment by karawin** [comment]
No, it is the current one for the moment. I said that because it is possible that your 1.4.2 points to a test station. (a wrong release at a moment). But try the normal update, i may have corrected it by placing a copy of the good bin.
