### ISSUE TITLE
Press Play while playing should not drop sound for 2 seconds 

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#43]
This could be reproduced with web  onclick="playStation()" , cli.play and hardware buttons 
I believe play button while we are already listening sound should pause

**Comment by karawin** [comment]
No. Play relaunch the station Stop is stop ;-)

**Comment by romankot** [comment]
stop is stop. Its working fine but play should not interrupt me from listening. Try the Prev command on first 
 station doesn't relaunch it , there is just no reaction

**Comment by karawin** [comment]
It's a feature....
