### ISSUE TITLE
After receive data to STM32 problem

### ISSUE THREAD

**Issue by ogggi** [karawin/Ka-Radio#44]
Hello

I have problem after turning on karadio. ESP(Nodemcu) normal playing, but STM32F103(with LCD ST7735,encoder and IR) after receive signal from serial ESP, itself stop.  Led diode on STM32 not blinking,but shines and lcd it stop. 
Sometimes normal working and all is good. All wires is good. 

thank you for answer

**Comment by karawin** [comment]
Is it the soft from https://github.com/karawin/karadio-addons ?
Not sure that it is a software problem.
If on a breadboard, check all lines and may be double the gnd and vcc.
I know that many breadboards are not very accurate (the long white from china).

**Comment by ogggi** [comment]
I havent on breadboard. All wires are soldering on board.  I have one question.  How you use library freertos with stm32?

**Comment by ogggi** [comment]
when I get reset on stm32 and receive data from esp ,stm32 freeze. I have two pieces stm32 and nodemcu, on both doing same.

**Comment by karawin** [comment]
I use it everyday on two prototypes.
I delivered again with 1.3 release.
May I forgot to update the github.
Please reload.

**Comment by karawin** [comment]
This issue is for addon, not for KaraDio itself. 
Please move it.
