### ISSUE TITLE
telnet sys.version doesn't work on 1.4.2

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#45]
Could not find the file with all command list (interfaces.txt) on github

**Comment by karawin** [comment]
![putty1](https://user-images.githubusercontent.com/7613191/28829404-e6c22a6c-76d3-11e7-86e0-bb3602472635.jpg)
![putty](https://user-images.githubusercontent.com/7613191/28829403-e6bf53d2-76d3-11e7-8d1d-bfc38b99a96e.jpg)
![putty2](https://user-images.githubusercontent.com/7613191/28829405-e6c91066-76d3-11e7-982b-e9645af58f60.jpg)

**Comment by karawin** [comment]
![putty1](https://user-images.githubusercontent.com/7613191/28829439-0697fb46-76d4-11e7-846d-6d05cce54b52.jpg)
![putty3](https://user-images.githubusercontent.com/7613191/28829441-06b08f58-76d4-11e7-9418-71f72077a291.jpg)
![putty2](https://user-images.githubusercontent.com/7613191/28829440-06aad978-76d4-11e7-9371-13c7c68da97c.jpg)

**Comment by karawin** [comment]
type 
help
or see the setting panel or directly http://karadio.karawin.fr/Interface.txt

**Comment by romankot** [comment]
I see nothing from sys.version. Setting on putty set exactly as you show. sys.version is not described in interfaces.txt

**Comment by karawin** [comment]
Telnet negociation mode passive too?

**Comment by romankot** [comment]
yes

**Comment by karawin** [comment]
This is a new command. Be sure to be with 1.4.1 or 1.4.2 release.

**Comment by romankot** [comment]
it works ! to be close
