### ISSUE TITLE
Radio hangup after several telnet "cli.vol-" commands in a row 

### ISSUE THREAD

**Issue by romankot** [karawin/Ka-Radio#46]

**Comment by karawin** [comment]
in a row????

**Comment by romankot** [comment]
try send several vol- one after one within 2 seconds

**Comment by karawin** [comment]
Not reproductive

**Comment by romankot** [comment]
Jean, try repeat vol- fast enough with upwards arrow. It seems that telnet get overloaded with fast input and drop off session. The radio itself keeps working but telnet session must be restarted

**Comment by karawin** [comment]
Not reproductive.
Tested many time. But...
Is it a telnet client problem?

**Comment by romankot** [comment]
i use putty

**Comment by romankot** [comment]
Jean, do you filter number of incoming web requests? Radio hung ups after several fast start/stop combination

**Comment by karawin** [comment]
May be filtered in case of extreme load. But in many case, just delayed.
Try the 1.5 release please.

**Comment by romankot** [comment]
not reproducible on 1.5 anymore. to be closed
