### ISSUE TITLE
A small question 

### ISSUE THREAD

**Issue by Edragon** [karawin/Ka-Radio#49]
Hi!!

Do you plan to replace the external flash? SPI flash like Winbond is much more cheaper and bigger, also what is the function of the flash? 

I have build the board, but play is not fluent probably because of the network, does any settings can help?

Thank you for the great project!

**Comment by karawin** [comment]
The external memory is not a flash one but a RAM.
It is not mandatory and is used to improve the stream buffer for eratic reception.
Thanks for your interrest.

**Comment by Edragon** [comment]
I see, it is pretty hard to get this, and expensive. Will try it, thank you again!
