### ISSUE TITLE
no connection to AP

### ISSUE THREAD

**Issue by acocalypso** [karawin/Ka-Radio#5]
Im having a hard time to get a connection. Sometimes it will connect to my WLAN but most time, the blue led (nodemcu v3) blinks a few times and then nothing happens. After restarting the esp **many** times it will reconnect to my wlan.

**Comment by karawin** [comment]
Hi,
This part is the espressif code.
Try to be closer of the AP?
Connect a terminal to see the log.

**Comment by v222008** [comment]
Hi. Developer fee (nodemcu v3)  is very demanding to the supply voltage, any voltage drop leads to restart or freezes chip.

**Comment by karawin** [comment]
Hi v222008
Right, but i made 4 protos without problem. The advantage of the v3 is that the usb 5v is available on pin VU (3). In case of connection with an usb port too weak, you can use hub with external power
Or a low cost https://fr.aliexpress.com/item/Best-price-30pcs-lot-MB102-Solderless-Breadboard-Power-Supply-Module-3-3V-or-5V/32351807367.html?spm=2114.13010608.0.0.VPHfoW

**Comment by acocalypso** [comment]
If its demanding to the suppy voltage, im going to test it again with a wallcharger.
Currently i was using my pc / notebook to power it on. 
Ill let you know if this will solve my issue.

**Comment by v222008** [comment]
Not the fact that USB cable or contacts in the micro yusb reliable. Try another USB cable or connect to a power supply of 5 volts.
But in the ideal case, connect the port to monitor and see the log...

**Comment by karawin** [comment]
No news, i close it
