### ISSUE TITLE
No sound :(

### ISSUE THREAD

**Issue by fdman** [karawin/Ka-Radio#51]
Hello,

I have a nodemcu v3 and VS1053, flash is ok, i think , I can open the webpage, I can select a radio and listen to it on the webpage but from the vs1053 I have no sound.
My output debug info is : 

External ram not detected

uart speed: 115200
Release 1.6.2, Revision 3
SDK 1.4.2(f57d61a)
data  : 0x3ffe8000 ~ 0x3ffe88fc, len: 2300
rodata: 0x3ffe8900 ~ 0x3ffea358, len: 6744
bss   : 0x3ffea358 ~ 0x3fff1778, len: 29728
heap  : 0x3fff1778 ~ 0x40000000, len: 59528
Heap size: 30616
size_map: 4
Eeprom_start: 3e0000
Eeprom_start1: 3d0000
Flash size: 4194304
t0 task: 3fff8a10
t1 task: 3fff8c98
t2 task: 3fff92b8
t3 task: 3fff96a8
t4 task: 3fff9cf0
Heap size: 23832
mode : sta(a0:20:a6:08:d7:e0)
add if0
SCI_Mode (0x4800) = 0x4802
SCI_Status (0x48) = 0x4C
VS Version (VS1053 is 4) = 4
SCI_ClockF = 0xB800
I2S Speed: 0
device: 3fffa788
plugin size 6350 3175 
plugin start: 7 1 8050 6
plugin size 234 117 
plugin start: 7 1 8f00 6
volume: 131
UART READY
AP1: WiFi-2.4-00F5, AP2: 
 AP1:Station Ip: 192.168.1.56
Trying WiFi-2.4-00F5 ,  I: 0 status: 1
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 4
pm open phy_2,type:2 0 0
cnt 

connected with WiFi-2.4-00F5, channel 3
ip:192.168.1.56,mask:255.255.255.0,gw:192.168.1.1
sleep enable,type: 2
No panel
ADC Div: 0 from adc: 0
autostart: playing:1, currentstation:2
I2S Speed: 0
##CLI.STOPPED# from playStationInt
##CLI.NAMESET#: 2 RTL2
##CLI.URLSET#: streaming.radio.rtl.fr
##CLI.PATHSET#: /rtl2-1-44-128.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 131
##CLI.STOPPED# from C_PLIST1
##CLI.URLSET#: ais.rtl.fr
##CLI.PATHSET#: /rtl2-1-44-128
##CLI.PORTSET#: 80
##CLI.ICY0#: RTL2 [MP3 128]
##CLI.ICY3#: http:\/\/www.rtl2.fr
##CLI.ICY5#: 128
##CLI.ICY6#: RTL2 [MP3 128]
##CLI.PLAYING#

##CLI.META#: 

Thank you for your help

**Comment by MarcLuc** [comment]
Hi,
This might be the same issue as mentioned in issue 34.   Try a sys.erase and sys.patch("0") to see if the problem is corrected.  full link below.

https://github.com/karawin/Ka-Radio/issues/34

**Comment by karawin** [comment]
sys.patch("0") is enough. May be an old vs1053. Some are seen unfortunately.

**Comment by fdman** [comment]
Hello,
Thank you for your answers.
I tested the command sys.patch("0") but still no sound, I think it comes from my vs1053, I will test with another model.

Congratulations, great project, I love, even if I'm beginner with esp;) and sorry for my bad English I'm Belgian

**Comment by karawin** [comment]
Est ce qu'il y a un ronflement avant l'init puis un silence ensuite?
Est ce que le jack est bien completement enfoncé?
check et recheck la connexion qui semble bonne car la carte est bien detectée et initialisée.
(I am French;-)

**Comment by fdman** [comment]
Hahahaha, désolé je savais pas :p en français tout de suite c'est plus facile :)
Non pas de ronflement, j'entends juste un tic puis plus rien.
J'ai vérifié pour le jack et la connexion aussi, tout me parait bon, la vs1053 est une LC Technology , je pense qu'elle a un problème, j'ai essayé de la tester avec un arduino et pas de son non plus.
Je vais m'en procurer une autre pour être certain

**Comment by fdman** [comment]
Bonjour,
Je viens de teste avec un autre VS1053 et tout est ok, c'etait bien mon VS1053 qui avait un problème :(.
J'ai testé aussi la version esp32 et impec aussi :p , je suis fan lol.
Un grand merci pour votre aide et je suis de très près le projet PCB :)

Au plaisir

**Comment by karawin** [comment]
Parfait, on peut clore cet issue.
A bientot sur facebook? https://www.facebook.com/groups/162949914181385

**Comment by fdman** [comment]
Oui vous pouvez fermer.
Pour ce qui est de facebook , j'y suis déja  ;) on est fan ou on ne l'est pas lol

A bientôt
