### ISSUE TITLE
wifi bridge between  landline phone and  mobile

### ISSUE THREAD

**Issue by mkeyno** [karawin/Ka-Radio#56]
Sorry to open a ticket for my question , actually I intend to make ESP8266 wifi bridge between my landline phone and my mobile , I've look for sufficient hardware for ADC at most 8bit bit stream and then use UDP to deliver audio package to mobile , also I've consider DFMT IC to dial or respond pulse tone . My problem is I don't have analog  design skill to find min and max specification needed for this project  , I don't know  how to select   analog circuits or Audio  codec IC's among plenty of possible options  for this matter and your advise really appreciated

**Comment by karawin** [comment]
A bit far of the KaRadio project. May be try to find a group on facebook to ask your question.
https://www.facebook.com/groups/1499045113679103/
