### ISSUE TITLE
##CLI.STOPPED# from clientConnect

### ISSUE THREAD

**Issue by DERLOUX** [karawin/Ka-Radio#58]
Bonjour

Depuis peu ma webradio ne fonctionne plus lorsque je lance la lecture d'une station j'ai systématiquement le message ##CLI.STOPPED# from clientConnect.
En mode monitoring tout fonctionne bien l'URL est bien joué

**Comment by karawin** [comment]
le log svp

**Comment by karawin** [comment]
No news.
Closed but reopen if still valid
