### ISSUE TITLE
Stop-Start gets invalid volume, no sound until sending volume command

### ISSUE THREAD

**Issue by j-levy** [karawin/Ka-Radio#60]
I noticed that, randomly, when I start playing, either with `cli.start` or with the play button on the website, it starts playing but no sound comes out. Using `cli.vol` I noticed that the volume reported is in the range of an unit16, and close to the max (I get 65532). I didn't expect that since I though it was in the range of uint8. Additionally, the volume reported when starting to play is OK (I guess it does something like cli.info when it starts); BUT it differs from the one reported by `cli.vol` and `cli.info` when you write these commands afterwards.
When changing the volume with `cli.vol+` or by moving the cursor in the website, it seems to get back on track, and sound comes out.
I have to tell that this problem didn't happen before, but I had to change my VS1053 board for another one. Previously I had [this board](https://fr.aliexpress.com/item/Free-shipping-VS1053-MP3-recording-module-development-board-on-board-recording-function/32223062819.html?spm=a2g0s.9042311.0.0.27426c37DAxgDm), and now, I have [this one](https://fr.aliexpress.com/item/VS1053-MP3-Module-Development-Board-w-On-Board-Recording-Function-SPI-Interface/1893615339.html?spm=a2g0s.9042311.0.0.40696c37xbFJYb). Could the problem related to the different board ?

See below what I get from the command line.

``` 
##CLI.STOPPED# from cli stop
#INFO:""#
##CLI.STOPPED# from playStationInt
##CLI.NAMESET#: 0 Tsumugi
##CLI.URLSET#: shelter.mahoro-net.org
##CLI.PATHSET#: /tsumugi.m3u
##CLI.PORTSET#: 8000
##CLI.OVOLSET#: 4
##CLI.VOL#: 155
##CLI.URLSET#: shelter.mahoro-net.org
##CLI.PATHSET#: /tsumugi
##CLI.PORTSET#: 8000
##CLI.STOPPED# from C_PLIST
##CLI.ICY0#: Tsumugi
##CLI.ICY3#: http:\/\/tsumugi.forum-thalie.fr
##CLI.ICY4#: anime
##CLI.ICY5#: 192
##CLI.ICY6#: Stream 192Kbps
##CLI.ICY7#:  channels=2;samplerate=44100;bitrate=192
##CLI.PLAYING#
##CLI.META#: Yoko Shimomura - The Edge of Green
cli.vol

##CLI.VOL#: 65532
> ##CLI.META#: Jingle Tsumugi - OH MY GOD
##CLI.META#: DAOKO×Yasuyuki Okamura - Step Up LOVE
cli.vol-

##CLI.VOL#: 155
```

**Comment by karawin** [comment]
Seems that the register on the vs103 is not well read.
