### ISSUE TITLE
Treble and Bass Control?

### ISSUE THREAD

**Issue by Primus007** [karawin/Ka-Radio#63]
is it possible to add a Treble and Bass Control for i2s output?

**Comment by karawin** [comment]
i2s output of the vs1053?
or i2s output of the KaRadio32?

**Comment by Primus007** [comment]
i2s Output on KaRadio32

**Comment by karawin** [comment]
So it is an issue for KaRadio32.
I have not planned to develop a dsp for that. 
Sorry

**Comment by Primus007** [comment]
and for the KaRadio?

**Comment by karawin** [comment]
Done by the vs1053.

**Comment by Primus007** [comment]
no bass and trebble for karadio i2s without vs1053? is bass/trebble possible for i2s or is it inpossible to code?

**Comment by karawin** [comment]
KaraDio don't use the mono, i2s output of the 8266.
The only i2s for KaraDio is done via the vs1053 I2S output..
