### ISSUE TITLE
Control Ka-radio via UART ???

### ISSUE THREAD

**Issue by thanhnc-iot** [karawin/Ka-Radio#64]
Dear sir,
In some cases, I need to monitor and control this board continuously while the unstable wifi connection.
Also, I need the function to play the next link when current link is no active.

**Comment by karawin** [comment]
http://karadio.karawin.fr/Interface.txt

**Comment by thanhnc-iot** [comment]
Thank sir.
I'd to modify and conpile this project in Windows OS, but I can not find out any IDE can do that, please help.
Tks in advance.

**Comment by karawin** [comment]
I don't use an ide.
Only https://notepad-plus-plus.org/
and https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup.html
