### ISSUE TITLE
Optimise web code

### ISSUE THREAD

**Issue by h1aji** [karawin/Ka-Radio#67]
Is there any chance to look at the web server?
First, It would be nice if CSS and JS would be optimised and there would be no need for yui compressor, which will simplify build.
Second maybe LUA should be considered instead of micropython?

Do you have any plans on implementing web control API?

**Comment by karawin** [comment]
yui compressor is only for optimization of the flash size. 
I am pretty sure it can work without it.

micropython? Where.
