### ISSUE TITLE
Scheduled sleep mode by time

### ISSUE THREAD

**Issue by v222008** [karawin/Ka-Radio#7]
Is it possible in next time to upgrade the sleep mode and the precisely scheduled time. For example OFF at 22:00 and ON at 8:00?

**Comment by karawin** [comment]
Hi,

No, The time is not available in the esp.
May be with NTP ....
I keep the idea.
Thanks

**Comment by karawin** [comment]
Sorry for my previous answer, it is wrong. In the javascript, this feature can be added.
I will write it in a future release.
