### ISSUE TITLE
Stuck at compiling "karadioU8STM32"

### ISSUE THREAD

**Issue by konzolec** [karawin/Ka-Radio#74]
I'm trying to connect b/w oled to karadio but i'm stuck at compiling.

karadioU8STM32: A complete interface with an oled B/W lcd, IR sensor, encoder knob. Based on a low cost STM32 board.

I always get the following error, and have no idea how to solve it.

`Arduino: 1.8.7 (Windows 10), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), STM32duino bootloader, 72Mhz (Normal), Smallest (default)"

WARNING: library U8glib claims to run on (avr, sam) architecture(s) and may be incompatible with your current board which runs on (STM32F1) architecture(s).
C:\Users\Marko-TEST\Documents\Arduino\portable\sketchbook\karadioU8STM32\karadioU8STM32.ino: In function 'void setup()':

karadioU8STM32:341:76: error: invalid conversion from 'uint8_t (*)(u8g_t*, uint8_t, uint8_t, void*) {aka unsigned char (*)(_u8g_t*, unsigned char, unsigned char, void*)}' to 'uint8_t {aka unsigned char}' [-fpermissive]

 U8GLIB_SSD1306_128X64 u8g((u8g_com_fnptr)u8g_com_hw_i2c_fn,U8G_I2C_OPT_NONE);

                                                                            ^

In file included from sketch\u8glibConf.h:8:0,

                 from C:\Users\Marko-TEST\Documents\Arduino\portable\sketchbook\karadioU8STM32\karadioU8STM32.ino:33:

C:\Users\Marko-TEST\Documents\Arduino\libraries\U8glib\src/U8glib.h:864:5: error:   initializing argument 1 of 'U8GLIB_SSD1306_128X64::U8GLIB_SSD1306_128X64(uint8_t, uint8_t, uint8_t)' [-fpermissive]

     U8GLIB_SSD1306_128X64(uint8_t cs, uint8_t a0, uint8_t reset = U8G_PIN_NONE) 

     ^

exit status 1
invalid conversion from 'uint8_t (*)(u8g_t*, uint8_t, uint8_t, void*) {aka unsigned char (*)(_u8g_t*, unsigned char, unsigned char, void*)}' to 'uint8_t {aka unsigned char}' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by vet20** [comment]
Hello! same error, what library did you use? I use u8glibConf.h in karadioU8STM32 folder.
