### ISSUE TITLE
Hard lags during playing.

### ISSUE THREAD

**Issue by Sera26** [karawin/Ka-Radio#78]
Dear All,

Playing of radio stations are lagging strongly, the streams are unpalatable.
I have already removed control buttons (ADC and GND bridged) and STM32+LCD but radio can't play stations continuously.
What can be the problem?

**Comment by karawin** [comment]
SHow the serial log.

**Comment by karawin** [comment]
Please update again. I modified the lwip lib.

**Comment by Sera26** [comment]
OK, thank you for help. By the way log doesn't show any mistake. Now it seems to be fine.

**Comment by karawin** [comment]
No error, just a network configuration  for some providers.

**Comment by karawin** [comment]
Tuned again. Please update.

**Comment by Sera26** [comment]
It seems much better. Thank you for help.
