### ISSUE TITLE
Fritzing drawing for Ka-Radio with Arduino Nano and Nokia display

### ISSUE THREAD

**Issue by 68erDirk** [karawin/Ka-Radio#8]
I created a fritzing drawing as stated above and the required vs1053 lcsoft-module (only breadboard view). Here are the files for your personal use.
![karawin_steckplatine](https://cloud.githubusercontent.com/assets/1450760/20361771/25a409d2-ac39-11e6-96bb-9033fcfa0a9c.jpg)
[Ka-Radio.zip](https://github.com/karawin/Ka-Radio/files/595679/Ka-Radio.zip)

**Comment by karawin** [comment]
Thanks.
