### ISSUE TITLE
URL longer than 116 chars / option to ota local changes

### ISSUE THREAD

**Issue by Ban-aan** [karawin/Ka-Radio#91]
Hi!

I want to connect to a radio station which requires a token. But this token is quite long, 205 chars. 
Is it possible to increase the limit of 116 chars URL's? Or is this limited by memory? 

Is there maybe an option to OTA flash local changes? That would make testing easier 👍🏻 

Best Regards,

**Comment by karawin** [comment]
Not possible, sorry.

**Comment by Ban-aan** [comment]
Instant play also doesn't play the URL. 
Also there is no option to OTA local changes?

**Comment by karawin** [comment]
OTA:no. Only by changing the code.
