### ISSUE TITLE
There is "% 20" in the station name instead of spaces.

### ISSUE THREAD

**Issue by hevet** [karawin/Ka-Radio#94]
@karawin When a station has spaces in its name, for example Radio RMF FM, the name in the display will appear as Radio% 20RMF% 20FM. Request for correction.

**Comment by karawin** [comment]
KaRadio don't have a display.
Request to change the issues in the right project.

**Comment by hevet** [comment]
@karawin Earlier versions of Karadio did not have this problem, it was displaying correctly, so it is more of a problem with karadio. ST7735 display.
