### ISSUE TITLE
NodeMCU wifi not visible after flash

### ISSUE THREAD

**Issue by Brahypelma** [karawin/Ka-Radio#98]
![image](https://user-images.githubusercontent.com/12914016/159137894-21f073b0-73b7-494b-bd28-94c2ac159faf.png)
Hello . After flash nodeMcu with latest config I dont see any new wifi
Console log:
![image](https://user-images.githubusercontent.com/12914016/159137937-fc2461bd-a0f4-48a2-b9d7-b6ff429c827e.png)
Checked with 2 different nodeMCUs. Pls help

**Comment by karawin** [comment]
Check esp_init_data_default.bin

**Comment by Brahypelma** [comment]
Oh I have NodeMCU with 4mb flash so need to pich in the ESP Downloader 32Mdit flash size. That resolved my issue

**Comment by aravindnc** [comment]
@Brahypelma Can you explain what you did to fix the issue ?

**Comment by Brahypelma** [comment]
@aravindnc I fixed my issue with setting correct flash size to flash it to right addresses. U need to pick up correct flash size

**Comment by aravindnc** [comment]
@Brahypelma Thanks for the response. But the new flash download tool does not have the flash size selection feature. It seem to do it automatically.
